const {chromium}=require('playwright');const fs=require('fs');const path=require('path');const http=require('http');const assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'), fixtures=path.join(__dirname,'mock-sites');
const results=[];let browser,server;
const run=async(name,fn)=>{try{await fn();results.push({name,status:'PASS'});console.log('PASS',name);}catch(e){results.push({name,status:'FAIL',error:e.message});console.log('FAIL',name,e.message);}};
(async()=>{
 server=http.createServer((req,res)=>{const file=path.join(fixtures,req.url==='/'?'index.html':req.url.split('?')[0]);if(!file.startsWith(fixtures)||!fs.existsSync(file)){res.writeHead(404);res.end('missing');return;}res.setHeader('Content-Type',file.endsWith('.wav')?'audio/wav':file.endsWith('.svg')?'image/svg+xml':'text/html');res.end(fs.readFileSync(file));});
 await new Promise(r=>server.listen(0,'127.0.0.1',r));browser=await chromium.launch({headless:true});const page=await browser.newPage({viewport:{width:1200,height:1050}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
 async function open(name='index.html'){
  await page.goto(`http://127.0.0.1:${server.address().port}/${name}`);
  await page.evaluate(()=>{window.sent=[];window.chrome={runtime:{sendMessage:async m=>{sent.push(m);return {ok:true}},onMessage:{addListener:fn=>window.listener=fn}}};const original=Element.prototype.attachShadow;Element.prototype.attachShadow=function(o){const shadow=original.call(this,o);window.testShadow=shadow;return shadow;};});
  await page.addScriptTag({path:path.join(root,'extension/content.js')});
 }
 const message=m=>page.evaluate(m=>new Promise(resolve=>{const r=listener(m,{},resolve);if(r!==true)setTimeout(resolve,100);}),m);
 const chord=async(a,b)=>{await page.keyboard.down(a);await page.keyboard.press(b);await page.keyboard.up(a);};
 await open();
 await run('Typing does not trigger ST or QA',async()=>{await page.locator('#typing').focus();await chord('s','t');await chord('q','a');assert.equal(await page.evaluate(()=>sent.length),0);await page.locator('h1').click();});
 await run('ST starts one job despite held key repeat',async()=>{await page.keyboard.down('s');await page.keyboard.down('t');await page.keyboard.down('t');await page.keyboard.up('t');await page.keyboard.up('s');assert.equal(await page.evaluate(()=>sent.filter(m=>m.type==='guided-start').length),1);});
 await run('Keyboard media selection preserves source identity',async()=>{await message({type:'guided-pick-media',runId:'one'});await page.keyboard.press('Enter');const m=await page.evaluate(()=>sent.find(m=>m.type==='guided-media'));assert.equal(m.media.label,'Museum announcement');assert.match(m.media.url,/museum.wav$/);assert.equal(m.runId,'one');});
 await run('Question crop includes options and negation',async()=>{await message({type:'guided-end-picker',runId:'one'});await message({type:'guided-question',runId:'one',source:'Museum announcement'});const b=await page.locator('#question').boundingBox();await page.mouse.move(b.x+2,b.y+2);await page.mouse.down();await page.mouse.move(b.x+b.width-2,b.y+b.height-2);await page.mouse.up();const q=await page.evaluate(()=>sent.filter(m=>m.type==='guided-question-ready').at(-1));assert.match(q.text,/NOT open/);assert.match(q.text,/C\. Sunday/);assert.doesNotMatch(q.text,/admission/);await page.screenshot({path:path.join(__dirname,'v03-selection.png')});});
 await run('Stale media URL is rejected',async()=>{const m=await page.evaluate(()=>sent.find(m=>m.type==='guided-media'));await page.locator('#audio').evaluate(el=>el.src='missing.wav');const r=await message({type:'validate-media',...m.media});assert.equal(r.ok,false);});
 await run('QA asks a new question and Escape cancels',async()=>{await chord('q','a');assert.equal((await page.evaluate(()=>sent.at(-1))).type,'qa-start');await message({type:'guided-question',runId:'two',source:'Previous transcript',reuse:true});await page.keyboard.press('Escape');assert.equal((await page.evaluate(()=>sent.at(-1))).type,'guided-cancel');assert.equal(await page.evaluate(()=>!!testShadow.querySelector('[style*="crosshair"]')),false);});
 await run('Answer stays hidden until reveal; reveal toggles',async()=>{assert.equal(await page.evaluate(()=>testShadow.textContent.includes('C. Sunday is closed.')),false);await message({type:'reveal-answer',text:'C. Sunday is closed.',source:'Museum announcement'});assert.equal(await page.evaluate(()=>testShadow.textContent.includes('C. Sunday is closed.')),true);await message({type:'reveal-answer',text:'C. Sunday is closed.',source:'Museum announcement'});assert.equal(await page.evaluate(()=>testShadow.textContent.includes('C. Sunday is closed.')),false);});
 await run('Image-only question reports visual content',async()=>{await open('visual.html');await message({type:'guided-question',runId:'visual',source:'Museum'});const b=await page.locator('#question').boundingBox();await page.mouse.move(b.x,b.y);await page.mouse.down();await page.mouse.move(b.x+b.width,b.y+b.height);await page.mouse.up();const q=await page.evaluate(()=>sent.at(-1));assert.equal(q.hasVisual,true);assert.equal(q.text,'');await page.locator('#question').screenshot({path:path.join(__dirname,'v03-question.png')});});
 await run('Keyboard rectangle supports resize and submit',async()=>{await open();await message({type:'guided-question',runId:'keyboard',source:'Museum'});await page.keyboard.press('Shift+ArrowDown');await page.keyboard.press('ArrowDown');await page.keyboard.press('Enter');const q=await page.evaluate(()=>sent.at(-1));assert.equal(q.type,'guided-question-ready');assert.equal(q.rect.height,535);assert.equal(q.rect.y,220);});
 await run('Page scroll invalidates captured region',async()=>{await page.evaluate(()=>{document.body.style.minHeight="3000px";window.scrollTo(0,100);});const r=await message({type:'guided-validate',runId:'keyboard'});assert.equal(r.ok,false);});
 await run('Signed uppercase audio download link is selectable',async()=>{await open();await page.evaluate(()=>{document.querySelectorAll('audio,a[download]').forEach(el=>el.remove());const a=document.createElement('a');a.href='/museum.WAV?token=test';a.textContent='Signed audio';document.body.prepend(a);});await message({type:'guided-pick-media',runId:'signed'});await page.keyboard.press('Enter');const m=await page.evaluate(()=>sent.find(m=>m.type==='guided-media'));assert.match(m.media.url,/museum.WAV\?token=test/);});
 await run('No browser JavaScript errors',async()=>assert.deepEqual(errors,[]));
})().catch(e=>{results.push({name:'harness',status:'FAIL',error:e.message});console.error(e.message)}).finally(async()=>{await browser?.close();server?.close();fs.writeFileSync(path.join(__dirname,'v03-browser-results.json'),JSON.stringify(results,null,2));if(results.some(r=>r.status==='FAIL'))process.exitCode=1;});
