const {chromium}=require('playwright');
const fs=require('fs'),path=require('path'),http=require('http'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),results=[];let browser,server,childServer,page;
const run=async(name,fn)=>{try{await fn();results.push({name,status:'PASS'});console.log('PASS',name);}catch(e){results.push({name,status:'FAIL',error:e.message});console.log('FAIL',name,e.message);}};
const childHTML=`<!doctype html><style>body{margin:40px}audio{display:block;width:300px;height:60px}</style><h2>Embedded audio</h2><audio controls src="/clip.wav" aria-label="Embedded clip"></audio><button id="focus">Focus child</button>`;
const html=()=>`<!doctype html><style>body{font:18px Arial;margin:40px}audio{display:block;width:300px;height:60px}#question{position:absolute;left:450px;top:170px;width:450px}iframe{margin-top:30px;width:380px;height:230px}#hidden{opacity:0}</style><h1>Content edge cases</h1><input id="input"><div id="edit" contenteditable="true">Editable text</div><audio controls src="/one.wav" aria-label="First clip"></audio><audio controls src="/two.wav" aria-label="Second clip"></audio><div id="question"><p>Which day is NOT open?</p><p>A. Monday</p><p>B. Tuesday</p><p id="hidden"><span>INVISIBLE WRONG ANSWER</span></p><p>C. Sunday</p></div><iframe src="http://127.0.0.1:${childServer.address().port}/child"></iframe>`;
async function open(){await page.goto(`http://127.0.0.1:${server.address().port}/`);for(const frame of page.frames()){await frame.evaluate(()=>{window.sent=[];window.replyError=null;window.chrome={runtime:{sendMessage:async m=>{sent.push(m);return m.type==='guided-media'&&replyError?{error:replyError}:{ok:true}},onMessage:{addListener:fn=>window.listener=fn}}};const attach=Element.prototype.attachShadow;Element.prototype.attachShadow=function(o){const shadow=attach.call(this,o);window.testShadow=shadow;return shadow;};});await frame.addScriptTag({path:path.join(root,'extension/content.js')});}}
const message=(frame,m)=>frame.evaluate(m=>new Promise(resolve=>{const pending=listener(m,{},resolve);if(pending!==true)setTimeout(()=>resolve(null),20);}),m);
const send=m=>message(page.mainFrame(),m);
const broadcast=m=>Promise.all(page.frames().map(f=>message(f,m)));
const chord=async(a,b)=>{await page.keyboard.down(a);await page.keyboard.press(b);await page.keyboard.up(a);};
async function cropQuestion(){const b=await page.locator('#question').boundingBox();await page.mouse.move(b.x,b.y);await page.mouse.down();await page.mouse.move(b.x+b.width,b.y+b.height);await page.mouse.up();return page.evaluate(()=>sent.findLast(m=>m.type==='guided-question-ready'));}
(async()=>{
 childServer=http.createServer((req,res)=>{res.setHeader('Content-Type','text/html');res.end(childHTML)});await new Promise(r=>childServer.listen(0,'127.0.0.1',r));
 server=http.createServer((req,res)=>{res.setHeader('Content-Type','text/html');res.end(html())});await new Promise(r=>server.listen(0,'127.0.0.1',r));
 browser=await chromium.launch({headless:true});page=await browser.newPage({viewport:{width:1100,height:850}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await run('Contenteditable typing never triggers ST/QA/RA',async()=>{await open();await page.locator('#edit').focus();await chord('s','t');await chord('q','a');await chord('r','a');assert.equal(await page.evaluate(()=>sent.length),0);});
 await run('Browser command question selection takes focus from input',async()=>{await open();await page.locator('#input').focus();await send({type:'guided-question',runId:'input',source:'Saved',reuse:true});await page.keyboard.press('Enter');assert.equal(await page.evaluate(()=>sent.at(-1)?.type),'guided-question-ready');});
 await run('Browser command media selection takes focus from contenteditable',async()=>{await open();await page.locator('#edit').focus();await send({type:'guided-pick-media',runId:'edit'});await page.keyboard.press('Enter');assert.equal(await page.evaluate(()=>sent.at(-1)?.type),'guided-media');});
 await run('Cross-origin iframe selection transfers keyboard to main question crop',async()=>{await open();const child=page.frames()[1];await broadcast({type:'guided-pick-media',runId:'iframe'});await child.locator('#focus').focus();await page.keyboard.press('Enter');assert.equal((await child.evaluate(()=>sent.at(-1))).media.label,'Embedded clip');await broadcast({type:'guided-end-picker',runId:'iframe'});await send({type:'guided-question',runId:'iframe',source:'Embedded clip'});await page.keyboard.press('Enter');assert.equal(await page.evaluate(()=>sent.at(-1)?.type),'guided-question-ready');});
 await run('Audio source highlight persists in originating iframe during download',async()=>{const child=page.frames()[1];await broadcast({type:'status',kind:'transcript',text:'Downloading selected audio'});assert.ok(await child.evaluate(()=>testShadow.querySelector('.box .tag')?.textContent.includes('Downloading selected audio')));});
 await run('Escape during processing sends active run cancellation',async()=>{await page.keyboard.press('Escape');assert.deepEqual(await page.evaluate(()=>sent.at(-1)),{type:'guided-cancel',runId:'iframe'});});
 await run('Keyboard alone reaches cross-origin iframe audio from top page',async()=>{await open();await page.locator('h1').click();await broadcast({type:'guided-pick-media',runId:'keyboard-frame'});assert.equal(await page.evaluate(()=>document.activeElement.id),'pagecue-overlay');await page.keyboard.press('ArrowDown');await page.keyboard.press('ArrowDown');await page.keyboard.press('Enter');await page.keyboard.press('Enter');const child=page.frames()[1];assert.equal((await child.evaluate(()=>sent.at(-1)))?.media?.label,'Embedded clip');});
 await run('Rejected blob source allows selecting next downloadable player',async()=>{await open();await page.evaluate(()=>{document.querySelector('audio').src='blob:http://example.invalid/test';replyError='Not a direct downloadable file';});await send({type:'guided-pick-media',runId:'blob'});await page.keyboard.press('Enter');await page.waitForTimeout(40);await page.evaluate(()=>replyError=null);await page.keyboard.press('ArrowDown');await page.keyboard.press('Enter');const m=await page.evaluate(()=>sent.findLast(m=>m.type==='guided-media'));assert.match(m.media.url,/two.wav$/);});
 await run('Protected source keeps picker usable for another source',async()=>{await open();await page.evaluate(()=>Object.defineProperty(document.querySelector('audio'),'mediaKeys',{value:{}}));await send({type:'guided-pick-media',runId:'protected'});await page.keyboard.press('Enter');await page.keyboard.press('ArrowDown');await page.keyboard.press('Enter');const m=await page.evaluate(()=>sent.findLast(m=>m.type==='guided-media'));assert.match(m?.media.url||'',/two.wav$/);});
 await run('Invisible ancestor text is excluded from question context',async()=>{await open();await send({type:'guided-question',runId:'visible',source:'Saved'});const q=await cropQuestion();assert.match(q.text,/NOT open/);assert.doesNotMatch(q.text,/INVISIBLE/);});
 await run('Keyboard selection skips invisible media candidates',async()=>{await open();await page.evaluate(()=>document.querySelector('audio').style.visibility='hidden');await send({type:'guided-pick-media',runId:'hidden'});await page.keyboard.press('Enter');const m=await page.evaluate(()=>sent.findLast(m=>m.type==='guided-media'));assert.match(m.media.url,/two.wav$/);});
 await run('Page URL change clears selections and cancels exact run',async()=>{await open();await send({type:'guided-pick-media',runId:'navigation'});await page.evaluate(()=>history.pushState({},'', '/other'));await page.keyboard.press('ArrowDown');assert.deepEqual(await page.evaluate(()=>sent.at(-1)),{type:'guided-cancel',runId:'navigation'});assert.equal(await page.evaluate(()=>testShadow.querySelectorAll('.box').length),0);});
 await run('Capture hide responds once even when animation frames are suspended',async()=>{await open();const response=await page.evaluate(async()=>{const original=requestAnimationFrame;let callback;window.requestAnimationFrame=fn=>{callback=fn;return 1;};let count=0;const started=performance.now();const result=await new Promise(resolve=>listener({type:'guided-hide'},{},value=>{count++;resolve(value);}));const elapsed=performance.now()-started;callback();callback();await new Promise(resolve=>setTimeout(resolve,30));window.requestAnimationFrame=original;return {result,elapsed,count,hidden:document.querySelector('#pagecue-overlay').style.visibility};});assert.equal(response.result.ok,true);assert.ok(response.elapsed>=100&&response.elapsed<1500);assert.equal(response.count,1);assert.equal(response.hidden,'hidden');});
 await run('No content script runtime errors',async()=>assert.deepEqual(errors,[]));
})().catch(e=>{console.error(e);results.push({name:'harness',status:'FAIL',error:e.message});}).finally(async()=>{await browser?.close();server?.close();childServer?.close();fs.writeFileSync(path.join(__dirname,'v031-content-results.json'),JSON.stringify(results,null,2));if(results.some(r=>r.status==='FAIL'))process.exitCode=1;});
