const {chromium}=require('playwright');const fs=require('fs');const path=require('path');const http=require('http');const assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'), fixtures=path.join(__dirname,'mock-sites');const results=[],apiCalls=[];let b,c,worker,options,session,server,site,page;let id='nejmlpiclajfnecfpiiafddcghffkhlb';let mode='normal',pending;
const pause=ms=>new Promise(r=>setTimeout(r,ms));
async function until(fn,label,ms=8000){const start=Date.now();while(Date.now()-start<ms){const v=await fn();if(v)return v;await pause(80);}throw Error('Timeout: '+label);}
const state=()=>worker.evaluate(()=>chrome.storage.local.get(['activeJob','lastJob','lastError','history','transcripts','activeTranscriptId','previousTranscriptId']));
const send=m=>options.evaluate(m=>chrome.runtime.sendMessage(m),m);
const chord=async(a,z)=>{await page.keyboard.down(a);await page.keyboard.press(z);await page.keyboard.up(a)};
async function clear(){pending?.();pending=null;await send({type:'cancel'});await pause(100);await worker.evaluate(()=>chrome.storage.local.set({activeJob:null,lastJob:null,lastError:'',history:[],transcripts:[{id:'seed',date:new Date().toISOString(),text:'The museum is closed on Sunday. Admission costs twelve euros.',title:'Saved museum',source:'Seed audio'}],activeTranscriptId:'seed',previousTranscriptId:null}));mode='normal';}
async function open(file='index.html',grant=true){page=await c.newPage();await page.setViewportSize({width:1200,height:1050});await page.goto(site+'/'+file);await page.bringToFront();await pause(200);return page;}
async function crop(selector='#question'){const q=await page.locator(selector).boundingBox();await pause(100);await page.mouse.move(q.x+3,q.y+3);await page.mouse.down();await page.mouse.move(q.x+q.width-3,q.y+q.height-3);await page.mouse.up();}
async function beginST(file='index.html',grant=true){await open(file,grant);await chord('s','t');await until(async()=>(await state()).activeJob?.phase==='select-media','media');await page.keyboard.press('Enter');await until(async()=>(await state()).activeJob?.phase==='select-question','question');await crop();}
async function done(){return until(async()=>{const s=await state();if(!s.activeJob&&s.lastError)throw Error(s.lastError);return !s.activeJob&&s.history?.length?s:null},'completion',15000);}
async function run(name,fn){if(process.env.PAGECUE_CASE_FILTER&&!new RegExp(process.env.PAGECUE_CASE_FILTER).test(name))return;await clear();try{await fn();results.push({name,status:'PASS'});console.log('PASS',name)}catch(e){results.push({name,status:'FAIL',error:e.message});console.log('FAIL',name,e.message)}finally{pending?.();pending=null;await send({type:'cancel'}).catch(()=>{});for(const p of c.pages())if(p!==options)await p.close().catch(()=>{});}}
(async()=>{
 server=http.createServer(async(req,res)=>{const url=new URL(req.url,'http://localhost');if(url.pathname.startsWith('/api/')){apiCalls.push({path:url.pathname,mode});for await(const part of req){}if(mode==='delay')await new Promise(r=>pending=r);if(res.destroyed)return;res.setHeader('Content-Type','application/json');if(mode==='rate-limit'&&url.pathname.endsWith('/chat/completions')){res.writeHead(429);res.end('{"error":{"message":"limited"}}');return;}res.end(JSON.stringify(url.pathname.endsWith('/audio/transcriptions')?{text:'The museum opens at nine on weekdays, ten on Saturday, and is closed on Sunday. Admission costs twelve euros.'}:{choices:[{message:{content:'C. Sunday'}}]}));return;}if(url.pathname==='/huge.wav'){res.writeHead(200,{'Content-Type':'audio/wav','Content-Length':'24000001'});res.end();return;}if(url.pathname==='/empty.wav'){res.writeHead(200,{'Content-Type':'audio/wav'});res.end();return;}if(url.pathname==='/fake.wav'){res.writeHead(200,{'Content-Type':'text/html'});res.end('<html>Please log in</html>');return;}const f=path.join(fixtures,url.pathname==='/'?'index.html':url.pathname);if(!f.startsWith(fixtures)||!fs.existsSync(f)){res.writeHead(404);res.end();return;}res.setHeader('Content-Type',f.endsWith('.wav')?'audio/wav':f.endsWith('.svg')?'image/svg+xml':'text/html');res.end(fs.readFileSync(f));});await new Promise(r=>server.listen(0,'127.0.0.1',r));site='http://127.0.0.1:'+server.address().port;
 b=await chromium.connectOverCDP('http://127.0.0.1:9340');c=b.contexts()[0];session=await b.newBrowserCDPSession();for(const ext of (await session.send('Extensions.getExtensions')).extensions||[])if(ext.name==='PageCue')await session.send('Extensions.uninstall',{id:ext.id}).catch(()=>{});const copy=fs.mkdtempSync(path.join(require('os').tmpdir(),'pagecue-fault-test-'));fs.cpSync(path.join(root,'extension'),copy,{recursive:true});const testManifest=JSON.parse(fs.readFileSync(path.join(copy,'manifest.json'),'utf8'));testManifest.host_permissions.push('<all_urls>');fs.writeFileSync(path.join(copy,'manifest.json'),JSON.stringify(testManifest));let provider=fs.readFileSync(path.join(copy,'providers.js'),'utf8');provider=provider.replace('https://api.openai.com/v1/',site+'/api/openai/').replace('https://openrouter.ai/api/v1/',site+'/api/openrouter/');fs.writeFileSync(path.join(copy,'providers.js'),provider);({id}=await session.send('Extensions.loadUnpacked',{path:copy}));
 options=await c.newPage();await options.goto(`chrome-extension://${id}/options.html`);worker=await until(()=>c.serviceWorkers().find(w=>w.url().includes(id)),'worker');
 const {defaults}=await import('../extension/providers.js');await worker.evaluate(config=>chrome.storage.local.set({providerConfig:config}),{...defaults,openai_key:'test-only-no-credential',openrouter_key:'test-only-no-credential',answer_provider:'openrouter'});
 await run('Brave ST: download, transcription, crop and answer',async()=>{await beginST();const s=await done();assert.equal(s.transcripts.length,2);assert.ok(s.history[0].questionImage);assert.equal(s.activeTranscriptId,s.transcripts[0].id);});
 await run('QA reuses transcript with no audio request',async()=>{const count=apiCalls.filter(x=>x.path.includes('transcriptions')).length;await open();await chord('q','a');await until(async()=>(await state()).activeJob?.phase==='select-question','QA');await crop();const s=await done();assert.equal(s.history[0].transcriptId,'seed');assert.equal(apiCalls.filter(x=>x.path.includes('transcriptions')).length,count);});
 await run('429 after transcription keeps recoverable transcript; retry does not retranscribe',async()=>{mode='rate-limit';await beginST();const failed=await until(async()=>{const s=await state();return !s.activeJob&&s.lastError?s:null},'429',15000);assert.match(failed.lastError,/429/);assert.equal(failed.activeTranscriptId,'seed');const count=apiCalls.filter(x=>x.path.includes('transcriptions')).length;mode='normal';await send({type:'retry'});const s=await done();assert.equal(s.history.length,1);assert.equal(apiCalls.filter(x=>x.path.includes('transcriptions')).length,count);assert.notEqual(s.activeTranscriptId,'seed');});
 await run('Cancel during API call ignores late completion',async()=>{mode='delay';await beginST();await until(()=>!!pending,'pending API');await send({type:'cancel'});pending?.();pending=null;await pause(300);const s=await state();assert.equal(s.activeJob,null);assert.equal(s.history.length,0);assert.equal(s.activeTranscriptId,'seed');});
 await run('Worker loss is recoverable and old transcript stays active',async()=>{mode='delay';await beginST();await until(()=>!!pending,'pending API');await worker.evaluate(()=>chrome.offscreen.closeDocument());const s=await send({type:'snapshot'});assert.match(s.lastError,/interrupted/);assert.equal(s.activeTranscriptId,'seed');});
 await run('Browser restart preserves transcript and does not replay an interrupted request',async()=>{
  mode='delay';await beginST();await until(()=>!!pending,'pending API');const count=apiCalls.length;
  await session.send('Browser.close');pending?.();pending=null;mode='normal';await pause(500);
  const profile=path.join(require('os').tmpdir(),'pagecue-v031-brave');const proc=require('child_process').spawn('C:/Program Files/BraveSoftware/Brave-Browser/Application/brave.exe',['--headless=new','--remote-debugging-port=9340','--enable-unsafe-extension-debugging','--no-first-run','--no-default-browser-check','--user-data-dir='+profile,'about:blank'],{windowsHide:true,stdio:'ignore',detached:true});proc.unref();
  b=await until(async()=>{try{return await chromium.connectOverCDP('http://127.0.0.1:9340')}catch{return null}},'Brave restart',10000);c=b.contexts()[0];session=await b.newBrowserCDPSession();await session.send('Extensions.loadUnpacked',{path:copy});options=await c.newPage();await options.goto(`chrome-extension://${id}/options.html`);worker=await until(()=>c.serviceWorkers().find(w=>w.url().includes(id)),'restarted worker');
  await send({type:'snapshot'});const d=await until(async()=>{const d=await state();return !d.activeJob&&d.lastError?d:null},'startup recovery');assert.match(d.lastError,/closed|interrupted/);assert.equal(d.activeTranscriptId,'seed');await pause(200);assert.equal(apiCalls.length,count);
 });
 await run('Audio source changed after selection is rejected before download',async()=>{await open();const count=apiCalls.length;await chord('s','t');await until(async()=>(await state()).activeJob?.phase==='select-media','media');await page.keyboard.press('Enter');await until(async()=>(await state()).activeJob?.phase==='select-question','question');await page.locator('#audio').evaluate(el=>{el.src='empty.wav';el.load();});await pause(200);await crop();const s=await until(async()=>{const s=await state();return !s.activeJob?s:null},'changed audio',10000);assert.match(s.lastError,/changed|select.*again/i);assert.equal(apiCalls.length,count);});
 for(const [source,pattern] of [['huge.wav',/24 MB/],['empty.wav',/empty/],['fake.wav',/audio|format|HTML|login/i]])await run('Reject '+source+' before transcription',async()=>{await open();await page.locator('#audio').evaluate((el,url)=>el.src=url,site+'/'+source);await pause(250);const count=apiCalls.length;await chord('s','t');await until(async()=>(await state()).activeJob?.phase==='select-media','media');await page.keyboard.press('Enter');await until(async()=>(await state()).activeJob?.phase==='select-question','question');await crop();const s=await until(async()=>{const s=await state();return !s.activeJob?s:null},'bad file',15000);assert.match(s.lastError,pattern);assert.equal(apiCalls.length,count);assert.equal(s.activeTranscriptId,'seed');});
 await run('Restore history and undo switches QA source',async()=>{await worker.evaluate(()=>chrome.storage.local.set({transcripts:[{id:'seed',text:'Old',title:'Old'},{id:'other',text:'Other',title:'Other'}]}));assert.equal((await send({type:'restore',id:'other'})).ok,true);let s=await state();assert.equal(s.activeTranscriptId,'other');assert.equal(s.previousTranscriptId,'seed');await send({type:'restore',id:s.previousTranscriptId});s=await state();assert.equal(s.activeTranscriptId,'seed');});
 await run('Question correction draft survives unrelated UI action',async()=>{await worker.evaluate(()=>chrome.storage.local.set({lastJob:{question:'Old question',context:'Old transcript'}}));const popup=await c.newPage();await popup.goto(`chrome-extension://${id}/popup.html`);await popup.locator('#question').fill('My corrected question');await popup.locator('h1').click();await worker.evaluate(()=>chrome.storage.local.set({lastError:'Unrelated status update'}));await pause(350);assert.equal(await popup.locator('#question').inputValue(),'My corrected question');});
})().catch(e=>{console.log('HARNESS',e.message);results.push({name:'harness',status:'FAIL',error:e.message})}).finally(async()=>{pending?.();if(worker)await worker.evaluate(()=>chrome.storage.local.remove('providerConfig')).catch(()=>{});if(session&&id)await session.send('Extensions.uninstall',{id}).catch(()=>{});await b?.close();server?.closeAllConnections();server?.close();fs.writeFileSync(path.join(__dirname,'v032-real-results.json'),JSON.stringify({results,apiCalls},null,2));if(results.some(r=>r.status==='FAIL'))process.exitCode=1;});
